import localFont from "next/font/local";
import { ThemeProvider } from "@/components/themeprovider"
import "./globals.css";
import { ModeToggle } from "@/components/themetogge";
import { Header } from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "bestedu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <Header />
          {children}
          <ModeToggle/>
        </ThemeProvider>
      </body>
    </html>
  );
}
